package com.legal.document.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Map;

@Service
public class BilingualPdfService {

    private static final Font TITLE_FONT = new Font(Font.HELVETICA, 18, Font.BOLD);
    private static final Font HEADING_FONT = new Font(Font.HELVETICA, 14, Font.BOLD);
    private static final Font NORMAL_FONT = new Font(Font.HELVETICA, 12, Font.NORMAL);
    private static final Font SMALL_FONT = new Font(Font.HELVETICA, 10, Font.ITALIC);

    /**
     * Generate bilingual PDF with user language and English versions
     */
    public byte[] generateBilingualPdf(
            String userLanguageContent,
            String englishContent,
            String userLanguage,
            String referenceNumber,
            Map<String, Object> metadata) throws DocumentException {

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4, 50, 50, 50, 50);

        try {
            PdfWriter.getInstance(document, outputStream);
            document.open();

            // Add header with reference number
            addHeader(document, referenceNumber);
            document.add(new Paragraph("\n"));

            // Add user language version
            addLanguageSection(document, userLanguageContent, userLanguage, true);

            // Add page break
            document.newPage();

            // Add English version
            addLanguageSection(document, englishContent, "English", false);

            // Add footer with disclaimer
            document.newPage();
            addDisclaimer(document);

            // Add metadata page
            if (metadata != null && !metadata.isEmpty()) {
                document.newPage();
                addMetadata(document, metadata);
            }

        } finally {
            document.close();
        }

        return outputStream.toByteArray();
    }

    private void addHeader(Document document, String referenceNumber) throws DocumentException {
        Paragraph header = new Paragraph();
        header.setAlignment(Element.ALIGN_CENTER);

        Chunk title = new Chunk("LEGAL DOCUMENT\n", TITLE_FONT);
        header.add(title);

        if (referenceNumber != null) {
            Chunk refNum = new Chunk("Reference No: " + referenceNumber + "\n", HEADING_FONT);
            header.add(refNum);
        }

        String dateStr = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));
        Chunk date = new Chunk("Generated on: " + dateStr, SMALL_FONT);
        header.add(date);

        document.add(header);

        // Add separator line
        Paragraph separator = new Paragraph("_".repeat(80), SMALL_FONT);
        separator.setAlignment(Element.ALIGN_CENTER);
        document.add(separator);
    }

    private void addLanguageSection(Document document, String content, String languageName, boolean isUserLanguage)
            throws DocumentException {

        // Section header
        Paragraph sectionHeader = new Paragraph();
        sectionHeader.setAlignment(Element.ALIGN_CENTER);

        String headerText = isUserLanguage
                ? "Version in " + getLanguageDisplayName(languageName) + " (For Your Understanding)"
                : "English Version (For Official Submission)";

        Chunk headerChunk = new Chunk(headerText + "\n\n", HEADING_FONT);
        sectionHeader.add(headerChunk);
        document.add(sectionHeader);

        // Add content
        Paragraph contentPara = new Paragraph(content, NORMAL_FONT);
        contentPara.setAlignment(Element.ALIGN_JUSTIFIED);
        contentPara.setSpacingAfter(20);
        document.add(contentPara);
    }

    private void addDisclaimer(Document document) throws DocumentException {
        Paragraph disclaimerTitle = new Paragraph("IMPORTANT DISCLAIMER\n\n", HEADING_FONT);
        disclaimerTitle.setAlignment(Element.ALIGN_CENTER);
        document.add(disclaimerTitle);

        String disclaimerText = "This document has been auto-generated by an AI-powered legal assistance system " +
                "for informational and documentation purposes only. It does NOT constitute legal advice.\n\n" +
                "This document is intended to help you:\n" +
                "• Organize your facts and information\n" +
                "• Present your case in a structured format\n" +
                "• Approach police stations, courts, lawyers, or government authorities\n\n" +
                "IMPORTANT:\n" +
                "• This document should be reviewed by a qualified legal professional before submission\n" +
                "• Laws and procedures vary by jurisdiction and may change over time\n" +
                "• The system cannot predict legal outcomes or provide legal opinions\n" +
                "• For urgent or emergency situations, contact appropriate authorities immediately\n\n" +
                "By using this document, you acknowledge that:\n" +
                "• You understand this is not legal advice\n" +
                "• You will seek professional legal counsel for your specific situation\n" +
                "• The creators of this system are not liable for any outcomes resulting from use of this document\n\n"
                +
                "For legal advice specific to your situation, please consult a licensed attorney.";

        Paragraph disclaimer = new Paragraph(disclaimerText, SMALL_FONT);
        disclaimer.setAlignment(Element.ALIGN_JUSTIFIED);
        document.add(disclaimer);
    }

    private void addMetadata(Document document, Map<String, Object> metadata) throws DocumentException {
        Paragraph metadataTitle = new Paragraph("Document Information\n\n", HEADING_FONT);
        document.add(metadataTitle);

        for (Map.Entry<String, Object> entry : metadata.entrySet()) {
            String key = formatKey(entry.getKey());
            String value = entry.getValue() != null ? entry.getValue().toString() : "N/A";

            Paragraph item = new Paragraph(key + ": " + value, NORMAL_FONT);
            item.setSpacingAfter(5);
            document.add(item);
        }
    }

    private String getLanguageDisplayName(String languageCode) {
        switch (languageCode.toLowerCase()) {
            case "en":
                return "English";
            case "hi":
                return "Hindi (हिंदी)";
            case "ta":
                return "Tamil (தமிழ்)";
            case "te":
                return "Telugu (తెలుగు)";
            case "kn":
                return "Kannada (ಕನ್ನಡ)";
            case "ml":
                return "Malayalam (മലയാളം)";
            case "mr":
                return "Marathi (मराठी)";
            case "bn":
                return "Bengali (বাংলা)";
            case "gu":
                return "Gujarati (ગુજરાતી)";
            default:
                return languageCode.toUpperCase();
        }
    }

    private String formatKey(String key) {
        return key.substring(0, 1).toUpperCase() +
                key.substring(1).replace("_", " ").replace("-", " ");
    }
}
