"""
Satta Vizhi — Bilingual Document Generator
"""

import json
from datetime import date
from llm_provider import llm
from langchain_core.messages import HumanMessage


LANGUAGE_NAMES = {
    "en": "English", "hi": "Hindi",  "ta": "Tamil",
    "te": "Telugu",  "kn": "Kannada","ml": "Malayalam",
    "mr": "Marathi", "bn": "Bengali","gu": "Gujarati",
}

DISCLAIMER_EN = (
    "This document has been automatically generated by Satta Vizhi based solely on information "
    "provided by the user. It is intended for informational and documentation purposes only and "
    "does not constitute legal advice. Users are strongly advised to review or verify this document "
    "with a qualified legal professional before official submission."
)

DISCLAIMER_TRANSLATIONS = {
    "ta": (
        "இந்த ஆவணம் Satta Vizhi மூலம் பயனர் வழங்கிய தகவல்களின் அடிப்படையில் தானாக உருவாக்கப்பட்டது. "
        "இது தகவல் மற்றும் ஆவணத் தயாரிப்பு நோக்கத்திற்காக மட்டுமே வழங்கப்படுகிறது. "
        "இது சட்ட ஆலோசனையாக கருதப்படக்கூடாது. அதிகாரப்பூர்வமாக சமர்ப்பிப்பதற்கு முன் "
        "தகுதியான சட்ட நிபுணரால் சரிபார்க்கப்பட வேண்டும் என்று அறிவுறுத்தப்படுகிறது."
    ),
    "hi": (
        "यह दस्तावेज़ Satta Vizhi द्वारा उपयोगकर्ता द्वारा प्रदान की गई जानकारी के आधार पर "
        "स्वचालित रूप से तैयार किया गया है। यह केवल सूचना और दस्तावेज़ीकरण उद्देश्यों के लिए है "
        "और कानूनी सलाह नहीं है। आधिकारिक प्रस्तुति से पहले किसी योग्य कानूनी पेशेवर से "
        "समीक्षा कराने की सलाह दी जाती है।"
    ),
    "te": (
        "ఈ పత్రం Satta Vizhi ద్వారా వినియోగదారు అందించిన సమాచారం ఆధారంగా స్వయంచాలకంగా రూపొందించబడింది. "
        "ఇది సమాచార మరియు డాక్యుమెంటేషన్ ప్రయోజనాల కోసం మాత్రమే మరియు చట్టపరమైన సలహా కాదు."
    ),
    "kn": (
        "ಈ ದಾಖಲೆಯನ್ನು Satta Vizhi ಮೂಲಕ ಬಳಕೆದಾರರು ಒದಗಿಸಿದ ಮಾಹಿತಿಯ ಆಧಾರದ ಮೇಲೆ ಸ್ವಯಂಚಾಲಿತವಾಗಿ ರಚಿಸಲಾಗಿದೆ. "
        "ಇದು ಕೇವಲ ಮಾಹಿತಿ ಮತ್ತು ದಾಖಲಾತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ ಮತ್ತು ಕಾನೂನು ಸಲಹೆ ಅಲ್ಲ."
    ),
    "ml": (
        "ഈ രേഖ Satta Vizhi വഴി ഉപയോക്താവ് നൽകിയ വിവരങ്ങളുടെ അടിസ്ഥാനത്തിൽ "
        "സ്വയംചാലകമായി സൃഷ്ടിക്കപ്പെട്ടതാണ്. ഇത് വിവരണ, ഡോക്യുമെന്റേഷൻ ആവശ്യങ്ങൾക്ക് "
        "മാത്രമുള്ളതാണ്, നിയമ ഉപദേശമല്ല."
    ),
}


def get_disclaimer(lang: str) -> str:
    return DISCLAIMER_TRANSLATIONS.get(lang, DISCLAIMER_EN)


# ── Document type determination ──────────────────────────────────────────────

def determine_document_type(intent: str) -> str:
    if not intent:
        return "general_petition"
    il = intent.lower()

    if any(t in il for t in ["cyber", "online fraud", "upi fraud", "internet fraud", "phishing", "digital fraud"]):
        return "cyber_fraud_complaint"
    if any(t in il for t in ["theft", "stolen", "robbery", "burglary", "pickpocket"]):
        return "police_complaint_fir"
    if any(t in il for t in ["assault", "physical", "attack", "hit", "beat"]):
        return "police_complaint_fir"
    if any(t in il for t in ["consumer", "product", "defective", "refund", "faulty", "e-commerce"]):
        return "consumer_complaint"
    if any(t in il for t in ["rti", "right to information", "government information", "public information"]):
        return "rti_application"
    if any(t in il for t in ["landlord", "tenant", "rent", "deposit", "eviction", "lease"]):
        return "legal_notice"
    # Workplace / employment issues → legal notice to employer, NOT police FIR
    if any(t in il for t in ["workplace", "employer", "salary", "wrongful termination",
                               "verbal harassment", "verbal abuse", "office", "manager",
                               "employee", "job", "work", "labour", "labor"]):
        return "workplace_complaint"
    if any(t in il for t in ["harassment", "stalking", "domestic violence", "abuse"]):
        return "police_complaint_fir"
    if any(t in il for t in ["divorce", "maintenance", "custody", "matrimonial", "family"]):
        return "family_petition"
    if any(t in il for t in ["cheating", "fraud", "scam", "deceive", "misrepresent"]):
        return "police_complaint_fir"

    return "general_petition"


AUTHORITY_MAP = {
    "cyber_fraud_complaint":  "The Cyber Crime Cell",
    "police_complaint_fir":   "The Station House Officer",
    "consumer_complaint":     "The Consumer Dispute Redressal Commission",
    "rti_application":        "The Public Information Officer",
    "legal_notice":           "The Opposite Party",
    "workplace_complaint":    "The Human Resources Department / Internal Complaints Committee",
    "family_petition":        "The Family Court",
    "general_petition":       "The Concerned Authority",
}

TITLE_MAP = {
    "cyber_fraud_complaint":  "Cyber Fraud Complaint",
    "police_complaint_fir":   "First Information Report (FIR) Draft",
    "consumer_complaint":     "Consumer Complaint",
    "rti_application":        "Application under Right to Information Act, 2005",
    "legal_notice":           "Legal Notice",
    "workplace_complaint":    "Formal Workplace Harassment Complaint",
    "family_petition":        "Petition",
    "general_petition":       "Complaint / Petition",
}

# Who receives a copy / where to submit
SUBMISSION_GUIDANCE = {
    "cyber_fraud_complaint":  "Submit at the nearest Cyber Crime Police Station or online at cybercrime.gov.in",
    "police_complaint_fir":   "Submit at the nearest Police Station (Station House Officer)",
    "consumer_complaint":     "Submit at the District Consumer Dispute Redressal Commission",
    "rti_application":        "Submit to the Public Information Officer of the concerned department",
    "legal_notice":           "Send by registered post / courier to the opposite party",
    "workplace_complaint":    "Submit to your company's HR Department and Internal Complaints Committee (ICC)",
    "family_petition":        "File at the Family Court in your jurisdiction",
    "general_petition":       "Submit to the concerned government authority",
}


def generate_reference_number(doc_type: str) -> str:
    today = date.today()
    prefix_map = {
        "cyber_fraud_complaint": "SV/CC",
        "police_complaint_fir":  "SV/FIR",
        "consumer_complaint":    "SV/CON",
        "rti_application":       "SV/RTI",
        "legal_notice":          "SV/LN",
        "workplace_complaint":   "SV/WPC",
        "family_petition":       "SV/FAM",
        "general_petition":      "SV/GEN",
    }
    prefix = prefix_map.get(doc_type, "SV/DOC")
    return f"{prefix}/{today.year}/{today.strftime('%m%d')}/001"


# ── Document text generation ──────────────────────────────────────────────────

def generate_document_in_language(
    intent: str,
    facts: dict,
    language: str,
    doc_type: str,
    ref_number: str,
) -> str:
    lang_name  = LANGUAGE_NAMES.get(language, "English")
    authority  = AUTHORITY_MAP.get(doc_type, "The Concerned Authority")
    title      = TITLE_MAP.get(doc_type, "Complaint")
    guidance   = SUBMISSION_GUIDANCE.get(doc_type, "")
    today_str  = date.today().strftime("%d %B %Y")

    SKIP = {"", "null", "unknown", "not available", "not applicable", "none", "explicitly_denied"}
    facts_clean = {k: v for k, v in facts.items()
                   if v and str(v).strip().lower() not in SKIP}

    prompt = f"""You are 'Satta Vizhi', an Indian legal document drafting assistant.
You are NOT a lawyer. You do not give legal advice.

[TASK]
Draft a complete, professional, authority-ready legal document in {lang_name} language,
based STRICTLY on the confirmed facts listed below. Do not invent any fact.

[DOCUMENT DETAILS]
Reference Number : {ref_number}
Date             : {today_str}
Document Type    : {title}
Submit To        : {authority}
Submission Note  : {guidance}
Legal Issue      : {intent}

[ALL CONFIRMED FACTS — use ONLY these]
{json.dumps(facts_clean, ensure_ascii=False, indent=2)}

[REQUIRED DOCUMENT STRUCTURE — follow exactly, in this order]
1. TITLE: {title}
2. Reference No: {ref_number}  |  Region: [city/state]  |  Date: {today_str}
3. To: {authority}, [city/state]
4. From: [complainant full name], [city/state], Phone: [phone]
5. Subject: [one factual sentence summarising the complaint]
6. Salutation: Respected Sir/Madam,
7. Introduction: 1 paragraph — who you are and purpose of writing
8. Chronological Facts: Numbered list — each item is ONE clear fact. Use ONLY confirmed facts.
9. Impact / Harm Suffered: (if harm_description or similar facts are available)
10. Evidence Available: Bullet list of all evidence mentioned in facts
11. Witnesses: (if witness_details available)
12. Prayer / Request: Numbered list of specific, reasonable actions being requested
13. Closing: 1 polite sentence
14. Signature Block:
    [Complainant Full Name]
    Place: [City]
    Date: {today_str}
    Signature: ___________________________
15. Submission Note: {guidance}

[STRICT RULES]
- Write ENTIRELY in {lang_name}. Every word must be in {lang_name}.
- Use cautious language: "may relate to", "is commonly addressed under", "situations like this may involve"
- NEVER cite specific IPC section numbers or make legal conclusions.
- NEVER alter amounts, dates, names, or UPI IDs from the facts.
- If a detail is not in the facts, write [TO BE FILLED] — never invent.
- Plain text ONLY. No markdown, no **, no #, no bullet symbols (use plain dashes or numbers).
- Return ONLY the document text. No preamble, no explanation.
"""

    response = llm.invoke([HumanMessage(content=prompt)])
    return response.content.strip()


# ── Readiness score ───────────────────────────────────────────────────────────

def calculate_readiness_score(facts: dict) -> int:
    """
    Score based on what the user actually has as evidence.
    Looks across ALL fact keys, not just 'evidence_available'.
    """
    # Combine all text from all fact values into one searchable string
    all_text = " ".join(str(v).lower() for v in facts.values() if v)

    score = 0

    # Documentary evidence (25 pts)
    doc_keywords = ["agreement", "contract", "receipt", "bill", "invoice",
                    "letter", "notice", "order", "certificate", "deed"]
    if any(k in all_text for k in doc_keywords):
        score += 25

    # Digital / payment proof (25 pts)
    digital_keywords = ["screenshot", "email", "message", "whatsapp", "sms",
                        "chat", "upi", "transaction", "payment", "transfer",
                        "bank", "statement", "record", "log"]
    if any(k in all_text for k in digital_keywords):
        score += 25

    # Physical / media evidence (25 pts)
    media_keywords = ["photo", "video", "recording", "cctv", "audio",
                      "voice", "image", "clip", "footage"]
    if any(k in all_text for k in media_keywords):
        score += 25

    # Witness evidence (25 pts)
    witness_keywords = ["witness", "colleague", "person", "present",
                        "testimony", "statement", "deponent"]
    if any(k in all_text for k in witness_keywords):
        score += 25

    # Bonus: has personal details + incident date (document is well-formed)
    has_personal  = bool(facts.get("user_full_name")) and bool(facts.get("user_city_state"))
    has_date      = bool(facts.get("incident_date"))
    has_desc      = bool(facts.get("incident_description"))
    completeness_bonus = sum([has_personal, has_date, has_desc]) * 5  # up to +15

    final = min(score + completeness_bonus, 100)

    # Floor: if we have any facts at all, at least show 20
    if final == 0 and len(facts) >= 3:
        final = 20

    return final


# ── Main entry point ──────────────────────────────────────────────────────────

def generate_bilingual_document(intent: str, facts: dict, user_language: str) -> dict:
    doc_type   = determine_document_type(intent)
    ref_number = generate_reference_number(doc_type)

    readiness = calculate_readiness_score(facts)

    # User-language version
    user_lang_content = generate_document_in_language(
        intent, facts, user_language, doc_type, ref_number)

    # English version (skip duplicate generation if already English)
    if user_language == "en":
        english_content = user_lang_content
    else:
        english_content = generate_document_in_language(
            intent, facts, "en", doc_type, ref_number)

    disclaimer_user_lang = get_disclaimer(user_language)

    return {
        "user_language_content": user_lang_content,
        "english_content":       english_content,
        "document_type":         doc_type,
        "readiness_score":       readiness,
        "user_language":         user_language,
        "disclaimer_en":         DISCLAIMER_EN,
        "disclaimer_user_lang":  disclaimer_user_lang,
        "reference_number":      ref_number,
    }
